version: 2
jobs:
  build:
    docker:
      - image: cimg/elixir:1.14.3

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test

